esphome:
  name: btbridge

time:
  - platform: sntp
    id: sntp_time
    timezone: UTC
    on_time:
      # Every 2 minutes
      - seconds: 0
        minutes: /2
        then:
          - mqtt.publish_json:
              topic: ${mqtt_base_topic}/living_room_temperature/${mqtt_topic_postfix}
              retain: True
              payload: |-
                root["Time"] = id(sntp_time).now().strftime("%Y-%m-%dT%H:%M:%S").c_str();
                JsonObject XiaomiMijia = root.createNestedObject("XiaomiMijia");                
                XiaomiMijia["Temperature"] = id(living_room_temperature).state; 
                XiaomiMijia["Humidity"] = id(living_room_humidity).state; 
                root["TempUnit"] = "C";
      - seconds: 30
        minutes: /2
        then:
          - mqtt.publish_json:
              topic: ${mqtt_base_topic}/sleeping_room_temperature/${mqtt_topic_postfix}
              retain: True
              payload: |-
                root["Time"] = id(sntp_time).now().strftime("%Y-%m-%dT%H:%M:%S").c_str();
                JsonObject XiaomiMijia = root.createNestedObject("XiaomiMijia");                
                XiaomiMijia["Temperature"] = id(sleeping_room_temperature).state; 
                XiaomiMijia["Humidity"] = id(sleeping_room_humidity).state; 
                root["TempUnit"] = "C";

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

substitutions:
  mqtt_base_topic: "tele/btbridge"
  mqtt_topic_postfix: "SENSOR"

# Enable logging
logger:

mqtt:
  broker: 192.168.1.13
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: ${mqtt_base_topic}
  

ota:
  password: ""

wifi:
  ssid: "HomeGuest"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Btbridge Fallback Hotspot"
    password: "ZreDoY1Awr18"

web_server:
  port: 80

esp32_ble_tracker:

sensor:
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:CA:AE:41"    
    temperature:
      name: "Living Room Temperature"
      id: living_room_temperature              
    humidity:
      name: "Living Room Humidity"
      id: "living_room_humidity"
    battery_level:
      name: "Living Room Battery Level"
    battery_voltage:
      name: "Living Room Battery Voltage"
    signal_strength:
      name: "Living Room Signal"
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:E6:B0:EF"    
    temperature:
      name: "Sleeping Room Temperature"
      id: sleeping_room_temperature              
    humidity:
      name: "Sleeping Room Humidity"
      id: "sleeping_room_humidity"
    battery_level:
      name: "Sleeping Room Battery Level"
    battery_voltage:
      name: "Sleeping Room Battery Voltage"
    signal_strength:
      name: "Sleeping Room Signal"
    

