esphome:
  name: btbridge

time:
  - platform: sntp
    id: sntp_time
    timezone: UTC
##    on_time:
##      # Every 2 minutes
##      - seconds: 0
##        minutes: /2
##        then:
##          - mqtt.publish_json:
##              topic: ${mqtt_tasmota_base_topic}/living_room_temperature/${mqtt_tasmota_topic_postfix}
##              retain: True
##              payload: |-
##                root["Time"] = id(sntp_time).now().strftime("%Y-%m-%dT%H:%M:%S").c_str();
##                JsonObject XiaomiMijia = root.createNestedObject("XiaomiMijia");                
##                XiaomiMijia["Temperature"] = id(living_room_temperature).state; 
##                XiaomiMijia["Humidity"] = id(living_room_humidity).state; 
##                root["TempUnit"] = "C";
##      - seconds: 20
##        minutes: /2
##        then:
##          - mqtt.publish_json:
##              topic: ${mqtt_tasmota_base_topic}/sleeping_room_temperature/${mqtt_tasmota_topic_postfix}
##              retain: True
##              payload: |-
##                root["Time"] = id(sntp_time).now().strftime("%Y-%m-%dT%H:%M:%S").c_str();
##                JsonObject XiaomiMijia = root.createNestedObject("XiaomiMijia");                
##                XiaomiMijia["Temperature"] = id(sleeping_room_temperature).state; 
##                XiaomiMijia["Humidity"] = id(sleeping_room_humidity).state; 
##                root["TempUnit"] = "C";
##      - seconds: 40
##        minutes: /2
##        then:
##          - mqtt.publish_json:
##              topic: ${mqtt_tasmota_base_topic}/kitchen_temperature/${mqtt_tasmota_topic_postfix}
##              retain: True
##              payload: |-
##                root["Time"] = id(sntp_time).now().strftime("%Y-%m-%dT%H:%M:%S").c_str();
##                JsonObject XiaomiMijia = root.createNestedObject("XiaomiMijia");                
##                XiaomiMijia["Temperature"] = id(kitchen_temperature).state; 
##                XiaomiMijia["Humidity"] = id(kitchen_humidity).state; 
##                root["TempUnit"] = "C";

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

substitutions:
  device_id: "btbridge"
  mqtt_tasmota_base_topic: tele/${device_id}
  mqtt_esphome_base_topic: esphometele/${device_id}
  mqtt_tasmota_topic_postfix: "SENSOR"

# Enable logging
logger:

mqtt:
  broker: 192.168.1.13
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: ${mqtt_esphome_base_topic}
  

ota:
  password: ""

wifi:
  ssid: "HomeGuest"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Btbridge Fallback Hotspot"
    password: "ZreDoY1Awr18"

web_server:
  port: 80

esp32_ble_tracker:

sensor:
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:CA:AE:41"    
    temperature:
      name: "Living Room Temperature"
      id: living_room_temperature
      filters:
        - filter_out: nan
      accuracy_decimals: 1
      unit_of_measurement: '°C'
    humidity:
      name: "Living Room Humidity"
      id: "living_room_humidity"
      accuracy_decimals: 0
      unit_of_measurement: '%'
    battery_level:
      name: "Living Room Battery Level"
    battery_voltage:
      name: "Living Room Battery Voltage"
      accuracy_decimals: 2
    signal_strength:
      name: "Living Room Signal"
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:E6:B0:EF"    
    temperature:
      name: "Sleeping Room Temperature"
      id: sleeping_room_temperature              
      accuracy_decimals: 1
      unit_of_measurement: '°C'
    humidity:
      name: "Sleeping Room Humidity"
      id: "sleeping_room_humidity"
      accuracy_decimals: 0
      unit_of_measurement: '%'
    battery_level:
      name: "Sleeping Room Battery Level"
    battery_voltage:
      name: "Sleeping Room Battery Voltage"
      accuracy_decimals: 2
    signal_strength:
      name: "Sleeping Room Signal"
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:98:2E:5F"    
    temperature:
      name: "Kitchen Temperature"
      id: kitchen_temperature              
      accuracy_decimals: 1
      unit_of_measurement: '°C'
    humidity:
      name: "Kitchen Humidity"
      id: "kitchen_humidity"
      accuracy_decimals: 0
      unit_of_measurement: '%'
    battery_level:
      name: "Kitchen Battery Level"
    battery_voltage:
      name: "Kitchen Battery Voltage"
      accuracy_decimals: 2
    signal_strength:
      name: "Kitchen Signal"
    

